# Deep Learning
  * when ML fails to work then only Deeplearning comes to the picture .
  * It consist of Neural network.
  * What is neuron, connection of neurons called as Neural Network.


  ### There are three typtes :
                            * ANN
                            * CNN
                            * RNN

    * Ann work on Structered data set .
    * Cnn works on images .   
    * Rnn works on speech or text .

# Neural Network Architecture :

    * Single neural network Architectutre 
    
    * Multi neural network Architecture 

* Architecture are build of three layer INPUT LAYER, HIDDEN LAYER,   OUTPUT LAYER.

* I/P - H/L - O/L (Single layer Architecture)

* I/P - H/L1 - H/L2 - H/L3 - O/P (Multi layer Architecture)

#### Epochs = forward Propagation + Backwrad Propagation 

* when we send/pass  signal from 1 neuron to another neuron  weight will assign  at FP(forward Propagation) .

* in BACKPROPAGATION  weight are Adjusted .

* when we do more number of epochs  accuracy will increase .

# Ann(Artificial Neural Network)
* An Artificial Neural Network is a model inspired by how the human brain works.
* It consists of layers of “neurons” that learn patterns from data. 

###  Activation function 
* Activation function will implement in Hidden layer and output layer .
* Main purpose of Activation function is to introduce non-linearity .
* Sigmoid activation function(apply on output layer and it adjust outlier (Range=0 to 1))
* tanh activation(apply on o/p layer (Range = -1 to 1))
* Relu(Rectifier function) activation function (Formula (max(x,o))) here you will never get any -ve value. it apply on only hidden layer(RAnge = 0 to infinity).
* Leeky relu (While the data has any -ve values then we apply leeky relu). it alsoapply in hidden liyer .(Range = -1 to infinity)
* softmax(is  apply on o/p layer (* if thereis binary class thn apply sigmoidand if there is multiclass thn apply Softmax)).. the main advantage of using this is the output is in probabilities range (0 to 1).

* N.B : Except  softmax all  function are apply on binnary classification .
* we not apply every activation one time .

* Inteview Questions : Sigmoid fun vs tanh fun   and  relu vs leeky relu

### Formula : 
 * new weight = old weight - learningrate * (derivation of loss/derivation of old weight)

* Simple example

If:

    old weight = 0.5
    learning rate = 0.1
    gradient = 0.2

Then:


    new weight = 0.5 - (0.1 × 0.2)
           = 0.5 - 0.02
           = 0.48

### Venishing Gradiant Descend:
* new weight == old weight that problem is called vanishing gradiant descend(vgd) it causes the  stop of the epoc then accuracy will Decrease.
* why the vgd problem occours coz overfits of neural model (Here overfits means -Trend the model with more neuron) to tackle this type of situation we apply Dropout(Drop the neurons) or Reagularization(lasso,Redge)

* ANN we use for both Regression and classification .

# Code

### poc -1 (churn modelling)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.21.0'

In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,delhi,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,delhi,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,delhi,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,mumbai,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,delhi,Female,28,4,130142.79,1,1,0,38190.78,0

In [16]:
dataset.head()

,apst,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,delhi,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,bangalore,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,delhi,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,delhi,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,bangalore,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
X

array([[619, 'delhi', 'Female', ..., 1, 1, 101348.88],
       [608, 'bangalore', 'Female', ..., 0, 1, 112542.58],
       [502, 'delhi', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'delhi', 'Female', ..., 0, 1, 42085.58],
       [772, 'mumbai', 'Male', ..., 1, 0, 92888.52],
       [792, 'delhi', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [8]:
import sys
print(sys.executable)

!"{sys.executable}" -m pip install scikit-learn

c:\Users\Satyabrata Sahoo\AppData\Local\Programs\Python\Python310\python.exe
Requirement already satisfied: scikit-learn in c:\users\satyabrata sahoo\appdata\local\programs\python\python310\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\satyabrata sahoo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\satyabrata sahoo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\satyabrata sahoo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\satyabrata sahoo\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.5.3)

[notice] A new release of pip available: 22.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [20]:
X

array([[0.0, 1.0, 0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 1, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0, ..., 1, 0, 38190.78]],
      shape=(10000, 14), dtype=object)

In [21]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 0.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 0.0, 1.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
X

array([[0.0, 1.0, 0.0, ..., 1, 1, 101348.88],
       [1.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 1, 42085.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 92888.52],
       [0.0, 1.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 13), dtype=object)

In [23]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X = sc.fit_transform(X)

In [24]:
X

array([[-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 1.00280393, -1.00280393,  1.00280393, ..., -1.54776799,
         0.97024255,  0.21653375],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [-0.99720391,  0.99720391, -0.99720391, ..., -1.54776799,
         0.97024255, -1.00864308],
       [ 1.00280393, -1.00280393,  1.00280393, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [-0.99720391,  0.99720391, -0.99720391, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 15))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [26]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 15)
(2000, 15)
(8000,)
(2000,)

# ANN MODEL BUILDING ARCHITECTURE

In [27]:
ann = tf.keras.models.Sequential() #establishing layer one after another

* Here we  built a neutral network 
    * tf = backend 
    * keras = frontend
    * sequential means establish of the layers(i.e. created layer in memory)

In [28]:
ann.add(tf.keras.layers.Dense(units=10)) # input layer

* unit= 6 (i.e. 6 neurons in i/p layers)
* Dense is connected the neurons to the layers .

In [29]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu')) # Hidden layer1

In [30]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu')) #2nd hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #output layer

#### optimizer in Ann:
 * socastic gradient descend
 * adam
 * adagrad
 * adadelta
 * adamax
 * rmsprop

#### Loss :
  * Loss (or Loss Function) measures how far the model's prediction is from the actual answer.

  * Low loss → Predictions are close to actual values.
  * High loss → Predictions are far from actual values.
  * The goal of training is to minimize the loss.
  * regression loss --- mae,mse,logloss
  * classification  loss --- 
                            
                    * binary cross entropy(Use when there are 2 classes only.)

                   * category cross entropy(Use when there are more than 2 classes and labels are one-hot encoded.)

                   * sparse category cross entropy(Use when there are more than 2 classes and labels are integers, not one-hot encoded.)

In [32]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [33]:

ann.fit(X_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7588 - loss: 0.5371
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7999 - loss: 0.4510
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8070 - loss: 0.4336
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8185 - loss: 0.4239
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8251 - loss: 0.4160
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8282 - loss: 0.4102
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8317 - loss: 0.4053
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8347 - loss: 0.4013
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8351 - loss: 0.3975
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8363 - loss: 0.3935
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8361 - loss: 0.3881
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8403 - loss: 0.3824
Epoch 13/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8430 - loss: 0.3742
Epoch 14/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8480 - loss: 0.3640
Epoch 15/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8530 - loss: 0.3543
Epoch 16/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8594 - loss: 0.3475
Epoch 17/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8596 - loss: 0.3443
Epoch 18/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3423
Epoch 19/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8605 - loss: 0.3408
Epoch 20/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8594 - loss: 0.3404
Epoch 21/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8641 - loss: 0.3387
Epoch 22/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8614 - loss: 0.3393
Epoch 23/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8629 - loss: 0.3387
Epoch 24/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8637 - loss: 0.3387
Epoch 25/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8630 - loss: 0.3372
Epoch 26/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3374
Epoch 27/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8615 - loss: 0.3363
Epoch 28/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8626 - loss: 0.3365
Epoch 29/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8634 - loss: 0.3356
Epoch 30/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8631 - loss: 0.3363
Epoch 31/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3359
Epoch 32/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8611 - loss: 0.3351
Epoch 33/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8634 - loss: 0.3350
Epoch 34/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3351
Epoch 35/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3351
Epoch 36/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8620 - loss: 0.3348
Epoch 37/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8634 - loss: 0.3341
Epoch 38/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3346
Epoch 39/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8662 - loss: 0.3337
Epoch 40/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8630 - loss: 0.3338
Epoch 41/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3330
Epoch 42/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8641 - loss: 0.3341
Epoch 43/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3341
Epoch 44/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8646 - loss: 0.3339
Epoch 45/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8627 - loss: 0.3326
Epoch 46/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8629 - loss: 0.3336
Epoch 47/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8649 - loss: 0.3332
Epoch 48/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8621 - loss: 0.3321
Epoch 49/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8651 - loss: 0.3330
Epoch 50/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8630 - loss: 0.3326

In [34]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]

In [35]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1540   55]
 [ 209  196]]

In [36]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.868

## CNN(convolution neural network)

* Here input data is images, videos .

* Before CNN we understand about these two subject
                                             1. Image Processing

                                                2. Computer vision

1. image processing isa methd to perform some operation on images . 

2. Computer vision is one of the technique which help to create image preprocessing.it enable computers to identify and process images inthe sameway that human vision does .

* images is broken down into pixels and every pixel range is 0-255 .

* wehave 2D(Black and White ) and 3D(Blue,Green,Red) channel in Matplotlibb we have RGB But here we have BGR .

* if Image  is broken down into 2 row nad 2 column it said 2D picture .

* when we upadate a picture into a system it convert into Array thn this array broken into the form of pixels of  1's and 0's .

* who is doing this "Keras Framework" (Imageto Array ,Array to image convert) .

* At first Cnn will Work than Ann work .ANN workin ML but also use in CNN .

* There is nothing image Regression it always be image classification .

* N.B :
  * Ml is a method to perform  operation on labeled data .
  * nlp is a method to perform operation work on text .
  * Ann is a method to perform operation on large datasets.
  * CNN is a method toperform operation on unlabeled/unstructure Dataset .

### we have  4 layer in CNN Architecture :
    1. convolution
    2. Max Pooling 
    3. Flattening 
    4. Full connection

* in CNN there is a image(i/p) and this image  brokendown into input matrix (here input layer become input matrix) ,in Ann it called input layer but in cnn it called input matrix ,there is noconcept of hidden layer in Cnn instead of hiddenlayer there is fillter or  called Feature detector also called kernel .

* Instead of output layer itis called output matrix or feature map .

* In Ann Weights are adjusted by backpropagation  but in Cnn filter values are adjusted .

##### 1. Convolution layer :
          * convultion is a mathematical operation that allows the merging of two sets of information .

           * convolution layer  is a math opertion between i/p matrix and filter to generate o/p matrix . 

* There is a very important concept is here called STRIDING : stride donotes how many steps  we are moving in each step in convolution . Bydefault it is one .

* Stride in convolution operation controls Movement of the filter .  

* STRIDING FORMUlA : n - f+1
     * here n = dimmension of matrix 

               f = total no.of filter 

* According to this formula if i/p matrix is (6 * 6 matrix) then o/p matrix is ( 4* 4 matrix) .

* in this what ever image we have  in o/p matrix the clearity will less coz decrease of matrix size  , for this issue we introduce another concept called "PADDING" .

* in this concept we convert o/p matrix from (4 * 4) to (6 * 6) , [I/p = o/p] . for this we  add one step padding in all the side.

* padding is a process of adding zeros to the i/p matrix symmetrically. it create  extra space within an element . in contrast, margin creates extra space arround an element .

#### 2. MaxPolling :
* Max polling always apply after o/p layer or convolution layer .
* Max polling is a polling operation that calculate the maximum value for patches of a feature map and uses it to create a down simpled feature map .
* Max polling is always 2D channel .
* it pool big number from everymatrix which are created after convolution .

### 3. Flattenning Layer :
* Flattenning isused to convert 2D array from pooled futuremaps into a single long continous linear vector .
* np.flatten()
* it is used to make the multidimmensional input 1-D , commonly used in the transition  the convolution layer tothe full connected layer .

#### 4. Full connected :

* in this we try to  apply a neuralnetwork .
* Fully connected is nothing but Dense(Densly connected to the neurons) .

* N.B :
  * CNN always apply on last , where Ann apply on hidden and output  layer . 
  * CNN model not understand any picture but based on folder in understand (like happy / not happy).

* CNN model we can work using Tf& keras, opencv, yolo, mediapipe .

* For convolution layer use conv2d function .
* for max polling use maxpool2d function .
* for  flattening layer use flattrn function .
* for fully connection layer use (dense) function .

* in CNN we appied  relu and sigmoid Activation function coz  we have use binnary class classification .

* Till here from 1st  we feed the data  in every project  included ML, NLP, ANN, CNN  , these modelare pre-trained(i.e. user hassome data and user train the data ) .

##### Let's introduce Pre-trained Model :
  * in case we have 30 images ,built the model but model predict wrong coz we need more data to correct classification/prediction  .

  * for large image like 10lakh , 15lakh mannually is not possible  for this senario PRE-TRAINED model comes to the picture , where they had more image inside it .

  * These pretrained model is called TRANSFORMER .
  * gpt, bert, t5 etc are the nlptransformer , to understand more about transformer lets introduce keras library .

  *  in CNN layer we built one or two layer but when it come to 100  layer or above system will hang so here we depend on some pretarined model like VEG19 ,RestNet V2 .

  * in every pretarined model in keras Deeplearning application we have a Transformer called "imagenet" .
  * we also work on Fashion Mnist and Bitbucket . 

##### Imagenet :
  * it is a massive, widely used visual database designed for computer vision research,featuering over 14 million annoted image organized by wordnet hierarchies , which contain 1000 classes .

   * in here how we call 14 million image into my project which run in cpu  for this these 14 million image has converted in yaml file and it has some weights

### Trained model vs pretrained model vs llm
* Trained model : user / devloper trained the data . 
* Pre-trained model : model trained by somebody like imagenet .
* llm : The model pulled the data directly from the internet .

### Data Augumentation :
* we can't built CNN model using 1 image , so we generate multiple image from 1 image and then build CNN model this process is called data augumentation .
* it comes under Generative Ai . 


### Ai vs Gen Ai 

* In Ai devloper need to train the data(write Algo - build model - model will predict ) .
* In Gen ai ,Ai generate image without trained  by user .

## Multiclass Classification 

* Here we work with more than two class.

* lets introduce bitbuckey - it is a private repo we are using in the organization where github is a public . 

* N.B : training> Testing> Validation .

##### we do two project : 
                     1: Fruit class classification using tensorflow for Android app .
                    
                     2: Fashion Mnist using Tensorflow (ANN) .

# Computer Vision 

* In compuyer vision we use cv2 library .
* Computer vision is a field of AI that enables computers to interpret, analyze, and understand visual information from the world such as image and video .

* We can work on Image clasification or image Recognization using Tf&keras,cv2,yolo,mediapipe (These are bunch of framework ) .

###### Function of CV :
 * 1. cv2.imread() : read the image from specific path location .
 * 2. cv2.imshow() : show the image in new window .
 * 3. cv2.waitkey() : whenever window will open new image wait till infinity time .
 * 4. cv2.destroyAllWindows() : it will kkey all open window  .
 * 5. cv2.imwrite('output.png', input) : save the images.
 * 6. cv2.cvtColor() : it has 150 color .

#### Lets introduce a very powerfull library called"haarcascadeclassifier"

* it is object detection Algorithm .
* It is a fast,machine learning based object detection algorithm ,used to identify objects likie (face,eye,ear ) in images/vedio . 

* to detect face we apply a logic (X+h,Y+W).
* to detect eye we apply same logic in nested for loop 
* .detect multiclass() create boundary box of every objects .

#### Here want to intoduce another powerful library  called "cv2.videocapture- it capture the video " .

* if user pass the argument cv2.videocapture(0) - it will turn on ur system cemera and on the video . .

#### Ocr : (Optical character recognization)

* Text Extraction from Documents called OCR .
* in this we use Pytesseract library .

#### opencv have 7/8 tracking algorithim .

* 1. Boosting Tracker
* 2. MIL Tracker
* 3. Kcf Tracker 
* 4. CSRT Tracker
* 5. Medianflow Tracker 
* 6. TLD Tracker
* 7. MOSE Tracker
* 8. GOTRUN Tracker

* Here another library :
  * cv2.createBackgroundSubtractorMOG2 -- it give the moveable thing white and rest are black .

###  Ultralytics yolo 
* it is a very powerful library .

 * it will do object detection , image segmentation, image classification, pose estimation, create object broundry boxes, object tracking .

### Yolo  stands for you only look once 

* what ever dataset you can find the world relevant to DS,Ai,Gen ai whay every dataset you can find from  here .


* GPT,bert is transformer in NLP and Rnn.
* Gans,autoencover is transformer of generative Ai  and imagenet is transformer in computer vision .

# RNN
* It is advance NLP. it work on text data .
* In ANN - input layer -- Hidden layer -- output layer
* In CNN - input matrix -- filter -- output matrix -- maxpool - flatten -- fully connected .
* In RNN  -  input -- text preprocessing -- output 
* RNN also called sequence to sequence model coz everytime  it store previous output(not lose anything ) .
* AT last we should use softmax coz it always gone to be multiclass classification .
* RNN mainly work in 2 concept 
                     * 1. LSTM(long short term memory)
                     * 2. GRU(gated recurrant unit)

* LSTM - lstm have 3 gates 
                    * 1. input gate
                      * memory cell
                    * 3. output gate
                    * 4. Forget gate
* Live example : Gmail

* GRU have 2 gates 
             * 1. update gate(input + memory + output)
             * 2. reset gate (reset to new gmail id or....) 

* Gru is more advance but 99% lstm only use .

* NLP pre-trained model are BERT or GPT .
* computer vision  pretrained model are restnet /imagenet .